# Generated by Django 4.0.6 on 2022-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcarrera', models.CharField(max_length=100)),
                ('nombre', models.TextField()),
                ('n_corto', models.CharField(max_length=100)),
                ('imagen', models.TextField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcurso', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.TextField()),
                ('hora', models.CharField(max_length=100)),
                ('creditos', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
