# Generated by Django 4.0.6 on 2022-08-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='idcarrera',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='idcurso',
        ),
    ]
