# Generated by Django 4.0.6 on 2022-08-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_remove_carrera_idcarrera_remove_curso_idcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
